# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stellarcalibration.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StellarCalibrationDialog(object):
    def setupUi(self, StellarCalibrationDialog):
        StellarCalibrationDialog.setObjectName("StellarCalibrationDialog")
        StellarCalibrationDialog.resize(379, 241)
        self.verticalLayoutWidget = QtWidgets.QWidget(StellarCalibrationDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.x0Star_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x0Star_label.sizePolicy().hasHeightForWidth())
        self.x0Star_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x0Star_label.setFont(font)
        self.x0Star_label.setObjectName("x0Star_label")
        self.horizontalLayout_2.addWidget(self.x0Star_label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.nm0Star_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nm0Star_edit.sizePolicy().hasHeightForWidth())
        self.nm0Star_edit.setSizePolicy(sizePolicy)
        self.nm0Star_edit.setObjectName("nm0Star_edit")
        self.horizontalLayout.addWidget(self.nm0Star_edit)
        self.nm0StarSet_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nm0StarSet_button.sizePolicy().hasHeightForWidth())
        self.nm0StarSet_button.setSizePolicy(sizePolicy)
        self.nm0StarSet_button.setObjectName("nm0StarSet_button")
        self.horizontalLayout.addWidget(self.nm0StarSet_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(StellarCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(StellarCalibrationDialog)

    def retranslateUi(self, StellarCalibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        StellarCalibrationDialog.setWindowTitle(_translate("StellarCalibrationDialog", "Stellar Calibration"))
        self.label.setText(_translate("StellarCalibrationDialog", "Step 1. Click recognizable feature in star plot"))
        self.label_11.setText(_translate("StellarCalibrationDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">x</span><span style=\" font-size:14pt; vertical-align:sub;\">0</span><span style=\" font-size:14pt;\">=</span></p></body></html>"))
        self.x0Star_label.setText(_translate("StellarCalibrationDialog", "not set"))
        self.label_3.setText(_translate("StellarCalibrationDialog", " pixels"))
        self.label_2.setText(_translate("StellarCalibrationDialog", "Step 2. Set the corresponding wavelength"))
        self.label_10.setText(_translate("StellarCalibrationDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">λ</span><span style=\" font-size:14pt; vertical-align:sub;\">0</span><span style=\" font-size:14pt;\">=</span></p></body></html>"))
        self.nm0StarSet_button.setText(_translate("StellarCalibrationDialog", "Set"))
        self.pushButton.setText(_translate("StellarCalibrationDialog", "Continue"))
